name: app
on: workflow_dispatch
jobs:
  setVersions:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:20.04
        env:
          NODE_ENV: development
    steps:
    - name: Calculate version
      run: |
        echo "v0.1.0-rc"
