name: app
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  setVersions:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:20.04
        env:
          NODE_ENV: development
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Calculate version
      run: |
        ls -la
        echo "v0.1.0-rc"
