name: app
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  setVersions:
    runs-on: ubuntu-latest
    container:
        image: ubuntu:20.04
        env:
          NODE_ENV: development
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - id: semver-tag
      uses: gandarez/semver-action@master
      with:
        branching_model: "trunk-based"
    - name: "Created tag"
      run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"
    - name: List files
      run: |
        ls -la
